name: safebrowse
description: Flutter Android VPN based on OpenVPN Library.
publish_to: 'none'
version: 1.0.1+2

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  

dev_dependencies:
  flutter_test:
    sdk: flutter
  package_info: ^0.4.3
  introduction_screen: ^2.1.0
  flag: ^5.0.1
  country_icons: ^2.0.2
  firebase_core: ^1.8.0
  firebase_auth: ^3.1.4
  shared_preferences: ^2.0.7
  provider: ^6.0.1
  avatar_glow: ^1.2.0
  flutter_launcher_icons: ^0.9.2
  rename: ^1.3.1

flutter_icons:
  android: true
  image_path: "assets/logo.png"

flutter:
  uses-material-design: true
  assets:
    - "assets/"
    - "assets/logo.jpg"
    - "assets/logo.png"
    - "assets/vpn/"